//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesTV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoviesTV()
        {
            this.MovieTVActors = new HashSet<MovieTVActor>();
            this.MovieTVDirectors = new HashSet<MovieTVDirector>();
            this.MovieTVWriters = new HashSet<MovieTVWriter>();
        }
    
        public int MovieTVID { get; set; }
        public int DiscTypeID { get; set; }
        public string RegionCodeID { get; set; }
        public string UPC { get; set; }
        public int TitleTypeID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> Runtime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int StudioID { get; set; }
        public string TitleImage { get; set; }
        public bool IsSiteFeature { get; set; }
        public bool IsGenreFeature { get; set; }
        public int TitleStatusID { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Studio Studio { get; set; }
        public virtual TitleStatus TitleStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTVActor> MovieTVActors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTVDirector> MovieTVDirectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTVWriter> MovieTVWriters { get; set; }
        public virtual DiscType DiscType { get; set; }
        public virtual TitleType TitleType { get; set; }
        public virtual RegionCode RegionCode { get; set; }
    }
}
