//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreFrontEntities : DbContext
    {
        public StoreFrontEntities()
            : base("name=StoreFrontEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<MoviesTV> MoviesTVs { get; set; }
        public virtual DbSet<MovieTVActor> MovieTVActors { get; set; }
        public virtual DbSet<MovieTVDirector> MovieTVDirectors { get; set; }
        public virtual DbSet<MovieTVWriter> MovieTVWriters { get; set; }
        public virtual DbSet<Studio> Studios { get; set; }
        public virtual DbSet<TitleStatus> TitleStatuses { get; set; }
        public virtual DbSet<Writer> Writers { get; set; }
        public virtual DbSet<DiscType> DiscTypes { get; set; }
        public virtual DbSet<TitleType> TitleTypes { get; set; }
        public virtual DbSet<RegionCode> RegionCodes { get; set; }
        public virtual DbSet<MPAARating> MPAARatings { get; set; }
    }
}
